[tool.poetry]
name = "storycraftr"
version = "0.1.0"
description = "A CLI tool for writing books using OpenAI."
authors = ["Tu nombre <tuemail@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
openai = "1.51.2"  # Especificando la versi贸n de OpenAI
click = "8.1"      # Especificando la versi贸n de Click
markdown = "3.7"   # Especificando la versi贸n de Markdown
pandoc = "2.4"     # Especificando la versi贸n de Pandoc
rich = "^13.9.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[tool.poetry.scripts]
storycraftr = "storycraftr.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
